export const PROJECT = {
  name: "NIFTY Intelligence Terminal",
  stage: 4,
  currentStep: 22,
  primaryInstrument: "NIFTY 50",
  venue: "NSE",
  primaryTimeframe: "5m",
  contextTimeframes: ["15m", "1h"],
  mode: "research-only",
  featureVersion: "price_features.v1",
  labelVersion: "nifty_5m_atr_first_touch.v1",
  researchVersion: "ml_research.v1",
  calibrationVersion: "multiclass_temperature.v1",
  signalPolicyVersion: "wait_first_atr_policy.v1",
  priceActionVersion: "causal_market_structure.v1",
} as const;

export const STAGE_STEPS = [
  { number: 1, title: "Project foundation" },
  { number: 2, title: "Canonical market data" },
  { number: 3, title: "Candles and snapshots" },
  { number: 4, title: "API and live chart" },
  { number: 5, title: "History and features" },
  { number: 6, title: "ML and replay" },
  { number: 7, title: "Calibration and policy" },
  { number: 8, title: "Trading dashboard" },
  { number: 9, title: "Paper analytics" },
  { number: 10, title: "Security and deployment" },
  { number: 11, title: "Licensed live market adapter" },
  { number: 12, title: "Canonical history recovery" },
  { number: 13, title: "Real-data research" },
  { number: 14, title: "Probability diagnostics" },
  { number: 15, title: "Locked shadow model" },
  { number: 16, title: "Trade-aligned labels" },
  { number: 17, title: "Shadow forward runtime" },
  { number: 18, title: "Baseline-controlled research" },
  { number: 19, title: "Causal price action" },
  { number: 20, title: "Pooled directional stability" },
  { number: 21, title: "Event-based price action" },
  { number: 22, title: "Derivatives forward data" },
] as const;
